// 顶层构建文件，统一插件版本与依赖版本
plugins {
    id 'com.android.application' version '8.1.4' apply false
    id 'com.android.library' version '8.1.4' apply false
}

ext {
    // 统一各模块依赖版本，集中管理便于升级
    compileSdk = 33
    targetSdk = 33
    minSdk = 23

    appId = 'test.dou'
}

task clean(type: Delete) {
    delete rootProject.buildDir
}